version: '3.8'

services:
  auth-service:
    build:
      context: ./services/AuthService
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONDODB_URL=mongodb://mongodb:27017/auth-service # MongoDB connection string
      - JWT_SECRET=your_jwt_secret # Replace with your JWT secret
      - JWT_EXPIRE=1d # JWT expiration time
      - ADMIN_REGISTRATION_KEY=your_admin_key # Replace with your admin registration key
    depends_on:
      - database

  restaurant-service:
    build:
      context: ./services/RestaurentService
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONDODB_URL=mongodb://mongodb:27017/restaurant-service
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE=1d
      - ADMIN_REGISTRATION_KEY=your_admin_key
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      - database
      - auth-service

  delivery-service:
    build:
      context: ./services/DeliveryService
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONDODB_URL=mongodb://mongodb:27017/delivery-service
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE=1d
      - ADMIN_REGISTRATION_KEY=your_admin_key
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      - database
      - auth-service

  order-service:
    build:
      context: ./services/OrderService
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - MONDODB_URL=mongodb://mongodb:27017/order-service
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE=1d
      - ADMIN_REGISTRATION_KEY=your_admin_key
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      - database
      - auth-service

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - restaurant-service
      - delivery-service
      - order-service

  database:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: